# Generated by Django 5.0 on 2023-12-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_ticket',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='ticket_fee',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
