# Generated by Django 5.0 on 2023-12-30 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_creator_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendeee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=11)),
                ('gender', models.CharField(max_length=20)),
                ('payment_status', models.CharField(max_length=50, null=True)),
                ('event', models.ManyToManyField(null=True, to='events.event')),
            ],
        ),
        migrations.DeleteModel(
            name='Creator',
        ),
    ]
