# Generated by Django 5.0 on 2023-12-30 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_attendee_event_alter_attendee_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='regular',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='vip',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='vvip',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
